server:
  port: 8050
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ${JDBC_USERNAME:jwxt}
    password: ${JDBC_PASSWORD:1234}
    url: jdbc:mysql://${JDBC_URL:sql.7326it.club}:${JDBC_PORT:53306}/jwxt?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
security:
  sessions: stateless
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://it-auth/user
      prefer-token-info: false
      service-id: it-gateway
urls:
  anon:
    - /auth/**
    - /router/**
    - /swagger-resources/**
    - /swagger-ui.html
    - /*/v2/api-docs
    - /swagger/api-docs
    - /webjars/**
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wfu.it.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    meta-object-handler: com.wfu.it.config.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  config: classpath:logback.xml