server:
  port: 8060
spring:
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
logging:
  config: classpath:logback.xml

